travis:
  secure:
    BINSTAR_TOKEN: AsmgWJ2d0aafuiTxehtXeYeCf5+VzDUCMmvuxNK7DsTtwxUZ49/a5rEgPAvIqa23GntCTAwxxzLBxJilJ8wqZM/OjSi31xAJ8WlTDaoZkkwLUATBp+KA8AA/syiKS4cvulocCKoZvuVXYkX7ZrOOynYgsigUkzaAjJ2XlNCfdwtcqeEX/6fFNONeTd1AeLwv8vx+f5JiM47qEfJEnllnBtewodUl0+CB9nfOHJOp+xy+el+8oZgeM+C35X6S8p3xl6PIAx+xYY2gjIWb8K43nr5vkfTmwkInEyjI1CvXBRq+ugy7gIWNB6pIsZZL0ebv5fPcDoJROYSazhd5NkL2NduWjPVAyNJj1T3pdaz/o0KbVm2sGGUTAfprpU+Y11OkfhUYN5zhErGwYjHwqS1SyqtBFprRBNhpwfI1s2KprTpW7hsk0GepIpLK1tBV0UQv7QtVk9Iq+cC1lTQtS2UV5Y0MNwhSYHv69xgF7XGN3yiG63w6ndmn+N83kN7LWzBBh881d5tY9kzlqPf5ujrnCxWoKFwU5sVk9pdxo/YIGiKUmXJIcIjjR30T656okw11br4pQWq5iwfVoK6Nw2NWtFjaCufV+GH6fFbrA3ATZETj9i44ErNytAWn5ZxanPUj/BCkPTalK7GunmC3L7S/NWhHqQ45FBVZ/0HA/TMHIHw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
